pipeline {
    agent {
        node {
            label 'dev-server'
        }
    }
    environment {
        APP_NAME = "xai-occupation-analyser"
        MAJOR_RELEASE = 0.1
        DOCKER_TAG = "${MAJOR_RELEASE}.${env.BUILD_NUMBER}"
        DOCKER_REG = "harbor.skillab-project.eu"
        DOCKER_REPO = "/skillab-all/"
        DOCKER_REG_CREDS = "harbor-creds"
    }

    stages {
        // *************************
        // *** IMAGE BUILD STAGE ***
        // *************************
        stage("Build_Docker_Images"){
            steps {
                echo "***** Building Docker Image *****"
                sh "docker build -t ${APP_NAME}:test ."
            }
        }
		
		// **************************
        // *** RUN THE UNIT TESTS ***
        // **************************
        stage("Run_Unit_Tests"){
            steps {
                echo "***** Running Unit Tests *****"
				sh "docker run --rm -e PYTHONPATH=/app ${APP_NAME}:test pytest"
            }
        }

        // ****************************
        // *** Push Images In Harbor ***
        // ****************************
        stage("Push_Image"){
            when {
                environment name: "GIT_BRANCH", value: "origin/main"
            }
            steps {
                withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: "${DOCKER_REG_CREDS}", usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]){
                    echo "***** Push Docker Image *****"
                    sh 'docker tag ${APP_NAME}:test ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG}'
                    sh 'docker login ${DOCKER_REG} -u ${USERNAME} -p ${PASSWORD}'
                    sh 'docker push ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG}'
					
					// Also tag and push as latest
                    sh 'docker tag ${APP_NAME}:test ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:latest'
                    sh 'docker push ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:latest'
                }
            }
        }
        
        // **************
        // *** Deploy ***
        // **************
        stage("Deployment"){
            when {
                environment name: "GIT_BRANCH", value: "origin/main"
            }

            steps {
                withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: "${DOCKER_REG_CREDS}", usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]){
                    echo "***** Deploy Application *****"
                    sh 'docker login ${DOCKER_REG} -u ${USERNAME} -p ${PASSWORD}'
                    sh 'docker pull ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG}'
					sh 'docker stop ${APP_NAME} || true'
					sh 'docker rm ${APP_NAME} || true'
                    sh 'docker run -d --name ${APP_NAME} -p 8872:8872 ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG}'
                    sh 'docker ps'
                }
            }
        }
    }
    post{
        always {
            // Remove specific images
            sh 'docker rmi ${APP_NAME}:test || true'
        }
        failure {
            echo "Build failed. Cleaned up docker environment."
            sh 'docker rmi ${APP_NAME}:${DOCKER_TAG} || true'
            sh 'docker rmi ${APP_NAME}:latest || true'
        }
    }
}
